"use strict"; 

var arrayOfInitialContent = [
	{ 
		type: "coin", 
		title: "George VI. 1 shilling 1945.", 
		description: "George VI. 1 shilling 1945.",
		сountry_of_origin: "England", 
		year_of_manufacture: "XX century", 
		material: "Silver", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "20th-century", 
		data_material: "silver", 
		starting_price: "$6.00",
		image_1_src: "../images/Content/Coins/coin-1-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-1-2.jpg", 
		timer: 24
	},
	{ 
		type: "coin", 
		title: "FRG. 10 marks 1972.", 
		description: "FRG. 10 marks 1972.", 
		сountry_of_origin: "Germany", 			
		year_of_manufacture: "XX century", 			
		material: "Silver", 
		data_сountry_of_origin: "Germany", 
		data_year_of_manufacture: "20th-century", 
		data_material: "silver", 
		starting_price: "$7.50",
		image_1_src: "../images/Content/Coins/coin-2-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-2-2.jpg", 
		timer: 100
	},
	{ 
		type: "coin", 
		title: "Straits Settlements. George V. 10 cents 1927.", 
		description: "Straits Settlements. George V. 10 cents 1927.", 
		сountry_of_origin: "Malaysia", 			
		year_of_manufacture: "XX century", 			
		material: "Silver", 
		data_сountry_of_origin: "Malaysia", 
		data_year_of_manufacture: "20th-century", 
		data_material: "silver", 
		starting_price: "$7.00",
		image_1_src: "../images/Content/Coins/coin-3-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-3-2.jpg", 
		timer: 200
	},
	{ 
		type: "coin", 
		title: "Victoria. 1/2 farthing 1843.", 
		description: "Victoria. 1/2 farthing 1843.", 
		сountry_of_origin: "England", 			
		year_of_manufacture: "XIX century", 			
		material: "Copper", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "19th-century", 
		data_material: "copper", 
		starting_price: "$34.00",
		image_1_src: "../images/Content/Coins/coin-4-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-4-2.jpg", 
		timer: 300
	},
	{ 
		type: "coin", 
		title: "Victoria. 1 farthing 1896.", 
		description: "Victoria. 1 farthing 1896.", 
		сountry_of_origin: "England", 			
		year_of_manufacture: "XIX century", 			
		material: "Bronze", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "19th-century", 
		data_material: "bronze", 
		starting_price: "$34.00",
		image_1_src: "../images/Content/Coins/coin-5-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-5-2.jpg", 
		timer: 150
	},
	{ 
		type: "coin", 
		title: "25 dollars 2000. Proof.", 
		description: "25 dollars 2000. Proof.", 
		сountry_of_origin: "Liberia", 			
		year_of_manufacture: "XXI century", 			
		material: "Gold", 
		data_сountry_of_origin: "Liberia", 
		data_year_of_manufacture: "21st-century", 
		data_material: "gold", 
		starting_price: "$51.50",
		image_1_src: "../images/Content/Coins/coin-6-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-6-2.jpg", 
		timer: 220
	},
	{ 
		type: "coin", 
		title: "25 dollars 2001. Proof.", 
		description: "25 dollars 2001. Proof.", 
		сountry_of_origin: "Liberia", 			
		year_of_manufacture: "XXI century", 			
		material: "Gold", 
		data_сountry_of_origin: "Liberia", 
		data_year_of_manufacture: "21st-century", 
		data_material: "gold", 
		starting_price: "$52.00",
		image_1_src: "../images/Content/Coins/coin-7-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-7-2.jpg", 
		timer: 110
	},
	{ 
		type: "coin", 
		title: "Franz Joseph I. 1 Kreisser 1881.", 
		description: "Franz Joseph I. 1 Kreisser 1881.", 
		сountry_of_origin: "Austria", 
		year_of_manufacture: "XIX century", 
		material: "Copper", 
		data_сountry_of_origin: "Austria", 
		data_year_of_manufacture: "19th-century", 
		data_material: "copper", 
		starting_price: "$10.00",
		image_1_src: "../images/Content/Coins/coin-8-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-8-2.jpg", 
		timer: 50
	},
	{ 
		type: "coin", 
		title: "Medal: 100th anniversary of the birth of Emperor Alexander I 1877.", 
		description: "Medal: 100th anniversary of the birth of Emperor Alexander I 1877.", 
		сountry_of_origin: "Russia", 
		year_of_manufacture: "XIX century", 
		material: "Bronze", 
		data_сountry_of_origin: "Russia", 
		data_year_of_manufacture: "19th-century", 
		data_material: "bronze", 
		starting_price: "$500.00",
		image_1_src: "../images/Content/Coins/coin-9-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-9-2.jpg", 
		timer: 80
	},
	{ 
		type: "coin", 
		title: "Franz Joseph I. 1 ducat 1915.", 
		description: "Franz Joseph I. 1 ducat 1915.", 
		сountry_of_origin: "Austria", 
		year_of_manufacture: "XX century", 
		material: "Gold", 
		data_сountry_of_origin: "Austria", 
		data_year_of_manufacture: "20th-century", 
		data_material: "gold", 
		starting_price: "$115.00",
		image_1_src: "../images/Content/Coins/coin-10-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-10-2.jpg", 
		timer: 90
	},
	{ 
		type: "coin", 
		title: "Half-kopek 1928.", 
		description: "Half-kopek 1928.", 
		сountry_of_origin: "USSR", 
		year_of_manufacture: "XX century", 
		material: "Copper", 
		data_сountry_of_origin: "USSR", 
		data_year_of_manufacture: "20th-century", 
		data_material: "copper", 
		starting_price: "$20.00",
		image_1_src: "../images/Content/Coins/coin-11-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-11-2.jpg", 
		timer: 34
	},
	{ 
		type: "coin", 
		title: "Norfolk. George III. 1/2 penny 1792.", 
		description: "Norfolk. George III. 1/2 penny 1792.", 
		сountry_of_origin: "England", 
		year_of_manufacture: "XVIII century", 
		material: "Copper", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "18th-century", 
		data_material: "copper", 
		starting_price: "$22.00",
		image_1_src: "../images/Content/Coins/coin-12-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-12-2.jpg", 
		timer: 12
	},
	{ 
		type: "coin", 
		title: "Victoria. 1 penny 1841.", 
		description: "Victoria. 1 penny 1841.", 
		сountry_of_origin: "England", 
		year_of_manufacture: "XIX century", 
		material: "Bronze", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "19th-century", 
		data_material: "bronze", 
		starting_price: "$25.00",
		image_1_src: "../images/Content/Coins/coin-13-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-13-2.jpg", 
		timer: 260
	},
	{ 
		type: "coin", 
		title: "Somerset. George III. 1 farthing 1795.", 
		description: "Somerset. George III. 1 farthing 1795.", 
		сountry_of_origin: "England", 
		year_of_manufacture: "XVIII century", 
		material: "Copper", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "18th-century", 
		data_material: "copper", 
		starting_price: "$18.00",
		image_1_src: "../images/Content/Coins/coin-14-1.jpg", 
		image_2_src: "../images/Content/Coins/coin-14-2.jpg", 
		timer: 56
	},
	{ 
		type: "book", 
		title: "Antique large Bible brass corner clasps", 
		description: "This is a very large (13\" tall X 10 3/4\" wide and 3 5/8\" thick) family Holy Bible with leather covers and brass corner clasps. Very beautiful Bible. No printing date (c1880). Hinges are strong, covers firmly attached and open and close easily.    Many full page illustrations, some in color and 2 maps. Water stained on about 4 pages (9th pic.). Covers have some rub marks and fading but still very elegant. Excellent condition, strong hinges (opens and closes easily).", 
		сountry_of_origin: "USA", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "USA", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$375.00",
		image_1_src: "../images/Content/Books/book-1-1.jpg", 
		image_2_src: "../images/Content/Books/book-1-2.jpg", 
		image_3_src: "../images/Content/Books/book-1-3.jpg", 
		timer: 125
	},
	{ 
		type: "book", 
		title: "Western Medical Guide Book", 
		description: "Western Medical Guide Book Japanese Antique Woodblock Print Medicine 1874. 8 books set. Author: Druitt Robert.", 
		сountry_of_origin: "Japan", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "Japan", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$1.25",
		image_1_src: "../images/Content/Books/book-2-1.jpg", 
		image_2_src: "../images/Content/Books/book-2-2.jpg", 
		image_3_src: "../images/Content/Books/book-2-3.jpg", 
		timer: 321
	},
	{ 
		type: "book", 
		title: "Homeopathic HERBAL Anatomy DRUG Pharmacy Medical APOTHECARY", 
		description: "Homeopathic HERBAL Anatomy DRUG Pharmacy Medical APOTHECARY. Year Printed: 1875. Publisher: WILSTACH, BALDWIN & CO.Author: John C. Gunn", 
		сountry_of_origin: "USA", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "USA", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$250.00",
		image_1_src: "../images/Content/Books/book-3-1.jpg", 
		image_2_src: "../images/Content/Books/book-3-2.jpg", 
		image_3_src: "../images/Content/Books/book-3-3.jpg", 
		timer: 544
	},
	{ 
		type: "book", 
		title: "Incunable Book of Hours on VELLUM", 
		description: "c.1503 MEDIEVAL Incunable Book of Hours on VELLUM - ORIGINAL BINDING incunabula. Fragment - Only 25 leaves remain (though in original binding). Stained internally, many rubrications and illuminations have been rubbed off or otherwise damaged, entire quires have been removed from the binding (probably in the nineteenth-century), though not affecting stability of the text-block. Contemporary early 16th-century binding has been recently repaired around the hinges with new leather. A beautiful, though incomplete, example of a very early Hardouin book of hours on vellum. For consideration today is a medieval Book of Hours (Usage of Rome), printed c.1503 in Paris by Hardouin in Latin and partially in Middle French entirely ON VELLUM.", 
		сountry_of_origin: "France", 
		year_of_manufacture: "XV century", 
		data_сountry_of_origin: "France", 
		data_year_of_manufacture: "15th-century", 
		starting_price: "$800.00",
		image_1_src: "../images/Content/Books/book-4-1.jpg", 
		image_2_src: "../images/Content/Books/book-4-2.jpg", 
		image_3_src: "../images/Content/Books/book-4-3.jpg", 
		timer: 70
	},
	{ 
		type: "book", 
		title: "Homer Odyssey", 
		description: "Homer Odyssey 1488 Book XVII 1st Printed Edition in Greek Incunable Iliad", 
		сountry_of_origin: "England", 
		year_of_manufacture: "XIV century", 
		data_сountry_of_origin: "England", 
		data_year_of_manufacture: "14th-century", 
		starting_price: "$8000.00",
		image_1_src: "../images/Content/Books/book-5-1.jpg", 
		image_2_src: "../images/Content/Books/book-5-2.jpg", 
		image_3_src: "../images/Content/Books/book-5-3.jpg", 
		timer: 90
	},
	{ 
		type: "antique", 
		title: "Vintage Chinese Lacquer Vase & Wood Stand", 
		description: "Vintage Chinese Lacquer Vase & Wood Stand", 
		сountry_of_origin: "China", 
		year_of_manufacture: "XX century", 
		material: "Lacquer", 
		data_сountry_of_origin: "China", 
		data_year_of_manufacture: "20th-century", 
		data_material: "lacquer", 
		starting_price: "$27.00",
		image_1_src: "../images/Content/Antique/antique-2-1.jpg", 
		image_2_src: "../images/Content/Antique/antique-2-2.jpg", 
		image_3_src: "../images/Content/Antique/antique-2-3.jpg", 
		timer: 150
	},
	{ 
		type: "antique", 
		title: "Chinese antique porcelain pot vase", 
		description: "Chinese antique porcelain fine crack blue&white dragon design pot vase", 
		сountry_of_origin: "China", 
		year_of_manufacture: "XVII century", 
		material: "Porcelain", 
		data_сountry_of_origin: "China", 
		data_year_of_manufacture: "17th-century", 
		data_material: "porcelain", 
		starting_price: "$400.00",
		image_1_src: "../images/Content/Antique/antique-3-1.jpg", 
		image_2_src: "../images/Content/Antique/antique-3-2.jpg", 
		image_3_src: "../images/Content/Antique/antique-3-3.jpg", 
		timer: 112
	},
	{ 
		type: "antique", 
		title: "Chinese antique porcelain vase", 
		description: "Chinese antique ming chenghua famille five colored porcelain vase ", 
		сountry_of_origin: "China", 
		year_of_manufacture: "XVI century", 
		material: "Porcelain", 
		data_сountry_of_origin: "China", 
		data_year_of_manufacture: "16th-century", 
		data_material: "porcelain", 
		starting_price: "$550.00",
		image_1_src: "../images/Content/Antique/antique-4-1.jpg", 
		image_2_src: "../images/Content/Antique/antique-4-2.jpg", 
		image_3_src: "../images/Content/Antique/antique-4-3.jpg", 
		timer: 234
	},
	{ 
		type: "antique", 
		title: "Antique pair of Chinese Porcelain Vases", 
		description: "Wonderfull Antique pair of Chinese Porcelain Vases, 18th century Fine painting", 
		сountry_of_origin: "China", 
		year_of_manufacture: "XVIII century", 
		material: "Porcelain", 
		data_сountry_of_origin: "China", 
		data_year_of_manufacture: "18th-century", 
		data_material: "porcelain", 
		starting_price: "$370.00",
		image_1_src: "../images/Content/Antique/antique-5-1.jpg", 
		image_2_src: "../images/Content/Antique/antique-5-2.jpg", 
		image_3_src: "../images/Content/Antique/antique-5-3.jpg",
		timer: 21
	},
	{ 
		type: "painting", 
		title: "View of the Terreiro do Paco", 
		description: "LOUIS DODD - 1943-2006, View of the Terreiro do Paco (Palace Square in Lisbon), oil on wood, signed, Dim. - 41 x 64 cm", 
		сountry_of_origin: "Spain", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "Spain", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$2000.00",
		image_1_src: "../images/Content/Paintings/painting-1-1.jpg", 
		timer: 16
	},	
	{ 
		type: "painting", 
		title: "The Defensive Occupation of Madeira", 
		description: "LOUIS DODD - 1943-2006, \"The Defensive Occupation of Madeira\", oil on wood, signed, Dim. - 52 x 92 cm", 
		сountry_of_origin: "Spain", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "Spain", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$3000.00",
		image_1_src: "../images/Content/Paintings/painting-2-1.jpg", 
		timer: 75
	},	
	{ 
		type: "painting", 
		title: "Paisagem tropical (Tropical Landscape)", 
		description: "\"Paisagem tropical\" (\"Tropical Landscape\"), watercolour on card stock, European school, 19th/20th C., minor defects, unsigned, Dim. - 19 x 37 cm", 
		сountry_of_origin: "Europe", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "Europe", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$150.00",
		image_1_src: "../images/Content/Paintings/painting-3-1.jpg", 
		timer: 61
	},	
	{ 
		type: "painting", 
		title: "A Pier view - Paris", 
		description: "A Pier view - Paris, oil on cardboard, signed GILBERT GALLAND (probably Gilbert Galland - 1870-1956), Dim. - 16 x 24 cm", 
		сountry_of_origin: "France", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "France", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$200.00",
		image_1_src: "../images/Content/Paintings/painting-4-1.jpg", 
		timer: 38
	},	
	{ 
		type: "painting", 
		title: "A Landscape - Figures near the stream", 
		description: "A Landscape - Figures near the stream, oil on canvas, French school, 19th C., signed A. CHEVALIER, Dim. - 65,5 x 58 cm", 
		сountry_of_origin: "France", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "France", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$400.00",
		image_1_src: "../images/Content/Paintings/painting-5-1.jpg", 
		timer: 74
	},
	{ 
		type: "postage-stamp", 
		title: "Liechtenstein 1994 Inventions Science", 
		description: "Liechtenstein 1994 Inventions Science", 
		сountry_of_origin: "Liechtenstein", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "Liechtenstein", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$1.00",
		image_1_src: "../images/Content/Postage-stamps/postage-stamp-1-1.jpg", 
		timer: 101
	},
	{ 
		type: "postage-stamp", 
		title: "Australia 1931 Aviation * Continents Earth map", 
		description: "Australia 1931 Aviation * Continents Earth map", 
		сountry_of_origin: "Australia", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "Australia", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$10.00",
		image_1_src: "../images/Content/Postage-stamps/postage-stamp-2-1.jpg", 
		timer: 32
	},	
	{ 
		type: "postage-stamp", 
		title: "San-Marino 1892 1L Catalogue 500 Euro", 
		description: "San-Marino 1892 1L Catalogue 500 Euro", 
		сountry_of_origin: "San-Marino", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "San-Marino", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$70.00",
		image_1_src: "../images/Content/Postage-stamps/postage-stamp-3-1.jpg", 
		timer: 9
	},	
	{ 
		type: "postage-stamp", 
		title: "Australia States 1899 State Quinsland", 
		description: "Australia ШТАТЫ 1899 State Quinsland", 
		сountry_of_origin: "Australia", 
		year_of_manufacture: "XIX century", 
		data_сountry_of_origin: "Australia", 
		data_year_of_manufacture: "19th-century", 
		starting_price: "$1.50",
		image_1_src: "../images/Content/Postage-stamps/postage-stamp-4-1.jpg", 
		timer: 10
	},	
	{ 
		type: "postage-stamp", 
		title: "USSR. 1981 г. Prokofiev Composer", 
		description: "USSR. 1981 г. Prokofiev Composer", 
		сountry_of_origin: "USSR", 
		year_of_manufacture: "XX century", 
		data_сountry_of_origin: "USSR", 
		data_year_of_manufacture: "20th-century", 
		starting_price: "$1.00",
		image_1_src: "../images/Content/Postage-stamps/postage-stamp-5-1.jpg", 
		timer: 58
	}	
]; 